// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPVP8_IPg854qlTw9QVAJ_UKY_8dN7L3c',
    appId: '1:875093733946:web:1f0d925bdacdfc25d3fb03',
    messagingSenderId: '875093733946',
    projectId: 'spm-project-shoppingmate',
    authDomain: 'spm-project-shoppingmate.firebaseapp.com',
    storageBucket: 'spm-project-shoppingmate.appspot.com',
    measurementId: 'G-B530WN7XMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIBO_anYiRdFzNhX5QApLbD6eMfxFBIOc',
    appId: '1:875093733946:android:b7446768167e9831d3fb03',
    messagingSenderId: '875093733946',
    projectId: 'spm-project-shoppingmate',
    storageBucket: 'spm-project-shoppingmate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxkYmP-wGEo9nsnHVJLERxA--1ql9Uub4',
    appId: '1:875093733946:ios:8eea40257d5317bcd3fb03',
    messagingSenderId: '875093733946',
    projectId: 'spm-project-shoppingmate',
    storageBucket: 'spm-project-shoppingmate.appspot.com',
    iosBundleId: 'com.shoppingmallapp.shoppingMallApplication',
  );
}
